package formularios;

import clases.ImagenFondo;
import clases.bdConexion;
import clases.paciente;
import clases.reportePacientes;
import clases.reporteRecetasMedicas;
import clases.reporteTablasAuxiliares;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;


/**
 *
 * 
 */
public class frmPrincipal extends javax.swing.JFrame {

    bdConexion con;
    
    reportePacientes rPac= new reportePacientes();
    reporteTablasAuxiliares rTA = new reporteTablasAuxiliares();
    reporteRecetasMedicas rRM = new reporteRecetasMedicas();
    
    paciente pa= new paciente();
    Object[][] dtPaciente; //variable de tipo Object que almacena una matriz de datos
    int fila=-1;
    
    
    //variables booleanas para controlar los menus segun el usuario
    String cUser=null;

    String modP=null;
    String gC=null;
    String rC=null;    
    String reC=null;
    String modS=null;
    String modT=null;
    String modEs=null;
    String modM=null;
    String rep=null;    
    String modU=null;
    String modDE=null;
    String manBD=null;
    
    
    
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setTitle("Sistema de Clinica Odontológica");
        jdContenedor.setBorder(new ImagenFondo());
        mostrarFechaActual();
        mostrarHoraActual();
        updateTablaPacientes();
        txtlogico.setVisible(false);        
        frmWorking.setSize(510,230);
        frmBuscarPaciente.setSize(500,350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        frmBuscarPaciente = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        txtValorFiltro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        frmWorking = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnPacientes = new javax.swing.JButton();
        btnReservarCitas = new javax.swing.JButton();
        btnRealizarConsulta = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnTratamientos = new javax.swing.JButton();
        btnEspecialista = new javax.swing.JButton();
        btnExpedienteClinico = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jdContenedor = new javax.swing.JDesktopPane();
        txtlogico = new javax.swing.JTextField();
        lblEtiquetaReloj = new javax.swing.JLabel();
        lblFechaActual = new javax.swing.JLabel();
        mnPrincipal = new javax.swing.JMenuBar();
        jmPacientes = new javax.swing.JMenu();
        jmConsultas = new javax.swing.JMenu();
        jMenuGestionCitas = new javax.swing.JMenuItem();
        jMenuReservarCita = new javax.swing.JMenuItem();
        jMenuMedicamentos = new javax.swing.JMenu();
        jMenuMedicamentoMedicina = new javax.swing.JMenu();
        jMenuMedicinaAgregar = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmConfiguracion = new javax.swing.JMenu();
        jmUsuarios = new javax.swing.JMenu();
        jmAgregarUsuarios = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        frmBuscarPaciente.setTitle("Pacientes");
        frmBuscarPaciente.setBounds(new java.awt.Rectangle(300, 300, 400, 300));
        frmBuscarPaciente.setModal(true);
        frmBuscarPaciente.setResizable(false);
        frmBuscarPaciente.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                frmBuscarPacienteWindowActivated(evt);
            }
        });

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar por:"));

        txtValorFiltro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtValorFiltro.setForeground(new java.awt.Color(0, 0, 255));
        txtValorFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorFiltroKeyTyped(evt);
            }
        });

        tablaPacientes.setBackground(new java.awt.Color(255, 255, 204));
        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPacientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPacientes);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del Paciente:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECCIONE UN PACIENTE DE LA LISTA");

        javax.swing.GroupLayout frmBuscarPacienteLayout = new javax.swing.GroupLayout(frmBuscarPaciente.getContentPane());
        frmBuscarPaciente.getContentPane().setLayout(frmBuscarPacienteLayout);
        frmBuscarPacienteLayout.setHorizontalGroup(
            frmBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmBuscarPacienteLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(frmBuscarPacienteLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        frmBuscarPacienteLayout.setVerticalGroup(
            frmBuscarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmBuscarPacienteLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        frmWorking.setTitle("Procesando");
        frmWorking.setBackground(java.awt.SystemColor.activeCaption);
        frmWorking.setIconImage(null);
        frmWorking.setMinimumSize(new java.awt.Dimension(340, 115));
        frmWorking.setModal(true);
        frmWorking.setUndecorated(true);
        frmWorking.setResizable(false);
        frmWorking.setSize(new java.awt.Dimension(340, 115));
        frmWorking.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                frmWorkingWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                frmWorkingWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Este Proceso Tomará Algunos Minutos");

        jButton1.setText("SI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("NO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿Desea continuar?");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/warning.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout frmWorkingLayout = new javax.swing.GroupLayout(frmWorking.getContentPane());
        frmWorking.getContentPane().setLayout(frmWorkingLayout);
        frmWorkingLayout.setHorizontalGroup(
            frmWorkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmWorkingLayout.createSequentialGroup()
                .addGroup(frmWorkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frmWorkingLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmWorkingLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmWorkingLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmWorkingLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        frmWorkingLayout.setVerticalGroup(
            frmWorkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmWorkingLayout.createSequentialGroup()
                .addGroup(frmWorkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmWorkingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(frmWorkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frmWorkingLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frmWorkingLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(frmWorkingLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel5))))
                    .addGroup(frmWorkingLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Informatico de Control Odontológico");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(204, 204, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToolBar1.setRollover(true);

        btnPacientes.setBackground(java.awt.SystemColor.inactiveCaption);
        btnPacientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/72_Pacientes.png"))); // NOI18N
        btnPacientes.setText("Pacientes");
        btnPacientes.setFocusable(false);
        btnPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPacientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPacientes);

        btnReservarCitas.setBackground(java.awt.SystemColor.inactiveCaption);
        btnReservarCitas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnReservarCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/72_Citas2.png"))); // NOI18N
        btnReservarCitas.setText("Reservar Citas");
        btnReservarCitas.setFocusable(false);
        btnReservarCitas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReservarCitas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReservarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarCitasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReservarCitas);

        btnRealizarConsulta.setBackground(java.awt.SystemColor.inactiveCaption);
        btnRealizarConsulta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRealizarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/consulta_dental.png"))); // NOI18N
        btnRealizarConsulta.setText("Consultas");
        btnRealizarConsulta.setFocusable(false);
        btnRealizarConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRealizarConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRealizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarConsultaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRealizarConsulta);

        btnServicios.setBackground(java.awt.SystemColor.inactiveCaption);
        btnServicios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/72_serv.png"))); // NOI18N
        btnServicios.setText("Servicios");
        btnServicios.setFocusable(false);
        btnServicios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnServicios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnServicios);

        btnTratamientos.setBackground(java.awt.SystemColor.inactiveCaption);
        btnTratamientos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTratamientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/72tratamientos.png"))); // NOI18N
        btnTratamientos.setText("Tratamientos");
        btnTratamientos.setFocusable(false);
        btnTratamientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTratamientos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTratamientosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTratamientos);

        btnEspecialista.setBackground(java.awt.SystemColor.inactiveCaption);
        btnEspecialista.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEspecialista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/72_Especialista1.png"))); // NOI18N
        btnEspecialista.setText("Especialista");
        btnEspecialista.setFocusable(false);
        btnEspecialista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEspecialista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEspecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecialistaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEspecialista);

        btnExpedienteClinico.setBackground(java.awt.SystemColor.inactiveCaption);
        btnExpedienteClinico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExpedienteClinico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/72_expedienteClinico.png"))); // NOI18N
        btnExpedienteClinico.setText("Expediente Clinico");
        btnExpedienteClinico.setFocusable(false);
        btnExpedienteClinico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExpedienteClinico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExpedienteClinico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpedienteClinicoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExpedienteClinico);

        btnSalir.setBackground(java.awt.SystemColor.inactiveCaption);
        btnSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/72_Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        jdContenedor.setBackground(new java.awt.Color(153, 204, 255));
        jdContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtlogico.setEditable(false);
        jdContenedor.add(txtlogico);
        txtlogico.setBounds(50, 350, 98, 22);

        lblEtiquetaReloj.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        lblEtiquetaReloj.setForeground(new java.awt.Color(102, 102, 255));
        lblEtiquetaReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEtiquetaReloj.setText("jLabel4");
        jdContenedor.add(lblEtiquetaReloj);
        lblEtiquetaReloj.setBounds(10, 60, 800, 70);

        lblFechaActual.setFont(new java.awt.Font("Segoe UI", 3, 40)); // NOI18N
        lblFechaActual.setForeground(new java.awt.Color(102, 102, 255));
        lblFechaActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaActual.setText("jLabel4");
        jdContenedor.add(lblFechaActual);
        lblFechaActual.setBounds(10, 10, 800, 50);

        mnPrincipal.setBackground(java.awt.SystemColor.controlHighlight);
        mnPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jmPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/24_Pacientes.png"))); // NOI18N
        jmPacientes.setText("Pacientes");
        jmPacientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnPrincipal.add(jmPacientes);

        jmConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/24_Cita.png"))); // NOI18N
        jmConsultas.setText("Citas");
        jmConsultas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultasActionPerformed(evt);
            }
        });

        jMenuGestionCitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuGestionCitas.setText("Gestionar Citas");
        jMenuGestionCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionCitasActionPerformed(evt);
            }
        });
        jmConsultas.add(jMenuGestionCitas);

        jMenuReservarCita.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuReservarCita.setText("Reservar Cita");
        jMenuReservarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReservarCitaActionPerformed(evt);
            }
        });
        jmConsultas.add(jMenuReservarCita);

        mnPrincipal.add(jmConsultas);

        jMenuMedicamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/24_Tratamiento.png"))); // NOI18N
        jMenuMedicamentos.setText("Medicamentos");
        jMenuMedicamentos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuMedicamentoMedicina.setText("Medicinas");
        jMenuMedicamentoMedicina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuMedicinaAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuMedicinaAgregar.setText("Agregar/Modificar");
        jMenuMedicinaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMedicinaAgregarActionPerformed(evt);
            }
        });
        jMenuMedicamentoMedicina.add(jMenuMedicinaAgregar);

        jMenuMedicamentos.add(jMenuMedicamentoMedicina);

        mnPrincipal.add(jMenuMedicamentos);

        jmReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/24_Reportes.png"))); // NOI18N
        jmReportes.setText("Reportes");
        jmReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jmReportes.add(jSeparator1);

        mnPrincipal.add(jmReportes);

        jmConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/24_Configuracion.png"))); // NOI18N
        jmConfiguracion.setText("Configuracion");
        jmConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmUsuarios.setText("Usuarios");
        jmUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmAgregarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmAgregarUsuarios.setText("Agregar/Modificar");
        jmAgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAgregarUsuariosActionPerformed(evt);
            }
        });
        jmUsuarios.add(jmAgregarUsuarios);

        jmConfiguracion.add(jmUsuarios);

        mnPrincipal.add(jmConfiguracion);

        jmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/24_Salir.png"))); // NOI18N
        jmSalir.setText("Salir");
        jmSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jmSalir.add(jMenuSalir);

        mnPrincipal.add(jmSalir);

        setJMenuBar(mnPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
            .addComponent(jdContenedor, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //maximiza la pantalla
        setExtendedState(frmPrincipal.MAXIMIZED_BOTH);    
        try {
            accesoSistema();
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_formWindowOpened

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        System.exit(0);
        //cerrarAplicacion();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        // TODO add your handling code here:
        frmPaciente fPacien = new frmPaciente();
        jdContenedor.add(fPacien);
        fPacien.show();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnReservarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarCitasActionPerformed
        // TODO add your handling code here:
        frmCitas fCitas= new frmCitas();
        jdContenedor.add(fCitas);
        fCitas.show();
    }//GEN-LAST:event_btnReservarCitasActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratamientosActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnTratamientosActionPerformed

    private void btnEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecialistaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        frmEspecialista fEspecialista = new frmEspecialista();
        jdContenedor.add(fEspecialista);
        fEspecialista.show();
    }//GEN-LAST:event_btnEspecialistaActionPerformed

    private void btnRealizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarConsultaActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnRealizarConsultaActionPerformed

    private void jMenuMedicinaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMedicinaAgregarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuMedicinaAgregarActionPerformed
    
    /*TABLA PARA BUSCAR AL PACIENTE Y MOSTRAR SU EXPEDIENTE CLINICO O RECETA MEDICA SEGUN EL CASO*/
    private void tablaPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPacientesMouseClicked
        // TODO add your handling code here:
        // MUESTRA CADA REGISTRO SELECCIONADO EN LOS CAMPOS CORRESPONDIENTES DEL FORMULARIO
        fila= tablaPacientes.rowAtPoint(evt.getPoint());//obtiene el indice de la fila seleccionada
        
        if (fila>-1){

            /*colocamos en los campos del formulario, el valor correspondiente obtenido
            * de la posicion de la fila y de la posicion de la columna.
            */
            String ip=(String.valueOf(tablaPacientes.getValueAt(fila, 0)));                        
            if (txtlogico.getText().equals("0"))//mostar reporte receta por paciente
            {
                rRM.abrirReporteRecetaMedicaPorPaciente(ip);
                this.frmBuscarPaciente.dispose(); 
                txtlogico.setText("");
            }else
            {
                try {                    
                    rPac.abrirReporteExpedienteClinicoPaciente(ip);
                } catch (SQLException ex) {
                    Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.frmBuscarPaciente.dispose();
                txtlogico.setText("");
                
            }                                   
        }
    }//GEN-LAST:event_tablaPacientesMouseClicked

    private void btnExpedienteClinicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpedienteClinicoActionPerformed
        // TODO add your handling code here:
        txtlogico.setText("1");
        //updateTabla();
        frmBuscarPaciente.setVisible(true);
        //frmBuscarPaciente.show();
    }//GEN-LAST:event_btnExpedienteClinicoActionPerformed

    private void frmWorkingWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmWorkingWindowOpened
       
        
    }//GEN-LAST:event_frmWorkingWindowOpened

    private void frmWorkingWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmWorkingWindowActivated
        //frmWorking.setSize(340,120);
       // txtLogico.setText("3");              
    }//GEN-LAST:event_frmWorkingWindowActivated

    private void txtValorFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorFiltroKeyTyped
        
    }//GEN-LAST:event_txtValorFiltroKeyTyped

    private void frmBuscarPacienteWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frmBuscarPacienteWindowActivated
        updateTablaPacientes();
        //frmBuscarPaciente.setSize(500,350);
    }//GEN-LAST:event_frmBuscarPacienteWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
//        vaciarDB();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frmWorking.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jmAgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAgregarUsuariosActionPerformed
        // TODO add your handling code here:
        frmUsuarios fUsers=new frmUsuarios();
        jdContenedor.add(fUsers);
        fUsers.show();
    }//GEN-LAST:event_jmAgregarUsuariosActionPerformed

    private void jMenuGestionCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionCitasActionPerformed
        // TODO add your handling code here:
        frmGestionCitas fGC = new frmGestionCitas();
        jdContenedor.add(fGC);
        fGC.show();
    }//GEN-LAST:event_jMenuGestionCitasActionPerformed

    private void jMenuReservarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReservarCitaActionPerformed
        // TODO add your handling code here:
        frmCitas fCitas = new frmCitas();
        jdContenedor.add(fCitas);
        fCitas.show();
    }//GEN-LAST:event_jMenuReservarCitaActionPerformed

    private void jmConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmConsultasActionPerformed

    //METODO PARA ACTUALIZAR LOS REGISTROS DE LA TABLA buscar paciente
    private void updateTablaPacientes() {
        String[] columNames = {"idPaciente", "Nombre del paciente"};
        //usamos la funcion
        dtPaciente = pa.getDatos2Pacientes();

        // se colocan los datos en la tabla    
        DefaultTableModel datos = new DefaultTableModel(dtPaciente, columNames);
        tablaPacientes.setModel(datos);
        TableColumnModel columnModel = tablaPacientes.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(20);
        columnModel.getColumn(1).setPreferredWidth(200);        
    }
    
    public void setAnchoColummnas()
    {
        JViewport scroll = (JViewport)tablaPacientes.getParent();
        int ancho=scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna=tablaPacientes.getColumnModel();
        TableColumn columnaTabla;
        for(int i=0; i<tablaPacientes.getColumnCount();i++)
        {
            columnaTabla=modeloColumna.getColumn(i);
            switch(i)
            {
                case 0: anchoColumna=(30*ancho)/100;
                        break;
                case 1: anchoColumna=(70*ancho)/100;
                    break;
                                   
            }
            columnaTabla.setPreferredWidth(anchoColumna);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    
    //Metodo para validar al usuario y el acceso a los permisos que tiene en el sistema
    public void accesoSistema() throws SQLException
    {        
        try
        {
            con = new bdConexion();
            
            ResultSet resultado=null;
            PreparedStatement pstml=(PreparedStatement)            
            con.getConnection().prepareStatement("SELECT * FROM usuario WHERE  idUsuario='"+cUser+"'");
            resultado=pstml.executeQuery();
            int x=0;
            resultado.last();

            if(resultado.getRow()<=0)
            {
                JOptionPane.showMessageDialog(null,"Error, Nombre de Usuario incorrecto","SICO",1);
                
            }
            else
            {                
                resultado.beforeFirst();

                while(resultado.next())
                {
//                    modP= resultado.getString("modificarPaciente");
//                    gC= resultado.getString("gestionarCitas");
//                    rC= resultado.getString("reservarCitas");
//                    reC= resultado.getString("realizarConsultas");
//                    modS= resultado.getString("modificarServicios");                    
//                    modT= resultado.getString("modificarTratamientos");
//                    modEs= resultado.getString("modificarEspecialista");
//                    modM= resultado.getString("modificarMedicamentos");
//                    rep= resultado.getString("verImprimirReportes");
//                    modU= resultado.getString("modificarUsuarios");
//                    modDE= resultado.getString("modificarDatosEmpresa");
//                    manBD= resultado.getString("manipularBD");
                    
                    x++;
                }
                
                /*if (modP.equals("1"))
                {
                    jMenuAgregarPacientes.setEnabled(true);
                    btnPacientes.setEnabled(true);
                }else
                {
                    jMenuAgregarPacientes.setEnabled(false);
                    btnPacientes.setEnabled(false);
                }
                if (gC.equals("1"))
                {
                    jMenuGestionCitas.setEnabled(true);                    
                }else
                {
                    jMenuGestionCitas.setEnabled(false);                    
                }
                if (rC.equals("1"))
                {
                    jMenuReservarCita.setEnabled(true);
                    btnReservarCitas.setEnabled(true);
                }else
                {
                    jMenuReservarCita.setEnabled(false);
                    btnReservarCitas.setEnabled(false);
                }*/
//                if (reC.equals("1"))
//                {
//                    btnRealizarConsulta.setEnabled(true);
//                }else
//                {
//                    btnRealizarConsulta.setEnabled(false);
//                }
//                if (modS.equals("1"))
//                {
//                    btnServicios.setEnabled(true);
//                }else
//                {
//                    btnServicios.setEnabled(false);
//                }
//                //--------------------
//                if (modT.equals("1"))
//                {
//                    btnTratamientos.setEnabled(true);
//                }else
//                {
//                    btnTratamientos.setEnabled(false);
//                }
//                if (modEs.equals("1"))
//                {
//                    btnEspecialista.setEnabled(true);
//                }else
//                {
//                    btnEspecialista.setEnabled(false);
//                }
//                if (rep.equals("1"))
//                {
//                    jmReportes.setEnabled(true);                    
//                }else
//                {
//                    jmReportes.setEnabled(false);                    
//                }
                /*if (modU.equals("1"))
                {
                    jmUsuarios.setEnabled(true);
                }else
                {
                    jmUsuarios.setEnabled(false);
                }
                //-----------------------
                if (modDE.equals("1"))
                {
                    jmEmpresa.setEnabled(true);
                }else
                {
                    jmEmpresa.setEnabled(false);
                }                
                if (manBD.equals("1"))
                {
                    jmBaseDatos.setEnabled(true);
                }else
                {
                    jmBaseDatos.setEnabled(false);
                }  */              
            }
            pstml.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e.getMessage());
        }
            con.desconectar();        
        
    }
    /*Obtener Fecha del sistema actual*/
    public final void mostrarFechaActual(){
        String fecha = new SimpleDateFormat("EEEE dd 'de' MMMM 'del' YYYY").format(new Date());
        lblFechaActual.setText(fecha);
    }
    
    
    /*Metodo para mostrar la hora del sitema actual*/
    public final void mostrarHoraActual() {

        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss a");
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(500);
                        lblEtiquetaReloj.setText(formateador.format(LocalDateTime.now()));
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();

    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEspecialista;
    private javax.swing.JButton btnExpedienteClinico;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnRealizarConsulta;
    private javax.swing.JButton btnReservarCitas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnTratamientos;
    private javax.swing.JDialog frmBuscarPaciente;
    private javax.swing.JDialog frmWorking;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuGestionCitas;
    private javax.swing.JMenu jMenuMedicamentoMedicina;
    private javax.swing.JMenu jMenuMedicamentos;
    private javax.swing.JMenuItem jMenuMedicinaAgregar;
    private javax.swing.JMenuItem jMenuReservarCita;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane jdContenedor;
    private javax.swing.JMenuItem jmAgregarUsuarios;
    private javax.swing.JMenu jmConfiguracion;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmPacientes;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenu jmUsuarios;
    private javax.swing.JLabel lblEtiquetaReloj;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JMenuBar mnPrincipal;
    private javax.swing.JTable tablaPacientes;
    private javax.swing.JTextField txtValorFiltro;
    private javax.swing.JTextField txtlogico;
    // End of variables declaration//GEN-END:variables
}
